
name: Miatoll Kernel Build CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build_kernel:
    name: Build Kernel Task
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential flex bison lld llvm clang \
            libssl-dev libelf-dev libncurses-dev git \
            python3 zip curl tar ccache

      - name: Execute Build Script
        run: |
          chmod +x Hamza.sh
          ./Hamza.sh
        env:
          KBUILD_BUILD_USER: Hamza8702
          KBUILD_BUILD_HOST: GitHub-Actions

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stormbreaker-Kernel-Miatoll
          path: "*.zip"
          if-no-files-found: error


